stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.48.1-noble
  script:
    - npm ci
    - npx playwright test

  after_script:
    - node reporter.js
  artifacts:
    paths:
      - playwright-report
      - results.xml
    when: always
    expire_in: 1 day
    reports:
      junit: results.xml
